In [ ]:
import numpy as np
import pandas as pd
import plotly.express as px

In [ ]:
df = pd.read_csv('healthcare-dataset-stroke-data.csv')
df

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1
...,...,...,...,...,...,...,...,...,...,...,...,...
5105,18234,Female,80.0,1,0,Yes,Private,Urban,83.75,NaN,never smoked,0
5106,44873,Female,81.0,0,0,Yes,Self-employed,Urban,125.20,40.0,never smoked,0
5107,19723,Female,35.0,0,0,Yes,Self-employed,Rural,82.99,30.6,never smoked,0
5108,37544,Male,51.0,0,0,Yes,Private,Rural,166.29,25.6,formerly smoked,0
5109,44679,Female,44.0,0,0,Yes,Govt_job,Urban,85.28,26.2,Unknown,0

In [ ]:
df.dtypes

id                     int64
gender                object
age                  float64
hypertension           int64
heart_disease          int64
ever_married          object
work_type             object
Residence_type        object
avg_glucose_level    float64
bmi                  float64
smoking_status        object
stroke                 int64
dtype: object

In [ ]:
df['age'] = df['age'].astype('int64')

In [ ]:
df.isna()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,True,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
5105,False,False,False,False,False,False,False,False,False,True,False,False
5106,False,False,False,False,False,False,False,False,False,False,False,False
5107,False,False,False,False,False,False,False,False,False,False,False,False
5108,False,False,False,False,False,False,False,False,False,False,False,False
5109,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.isna().sum()

id                     0
gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level      0
bmi                  201
smoking_status         0
stroke                 0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 5110 non-null   int64
 1   gender             5110 non-null   object
 2   age                5110 non-null   int64
 3   hypertension       5110 non-null   int64
 4   heart_disease      5110 non-null   int64
 5   ever_married       5110 non-null   object
 6   work_type          5110 non-null   object
 7   Residence_type     5110 non-null   object
 8   avg_glucose_level  5110 non-null   float64
 9   bmi                4909 non-null   float64
 10  smoking_status     5110 non-null   object
 11  stroke             5110 non-null   int64
dtypes: float64(2), int64(5), object(5)
memory usage: 479.2+ KB

In [ ]:
df.nunique()

id                   5110
gender                  3
age                    83
hypertension            2
heart_disease           2
ever_married            2
work_type               5
Residence_type          2
avg_glucose_level    3979
bmi                   418
smoking_status          4
stroke                  2
dtype: int64

In [ ]:
df['work_type'].unique()

array(['Private', 'Self-employed', 'Govt_job', 'children', 'Never_worked'],
      dtype=object)

In [ ]:
df['gender'].unique()

array(['Male', 'Female', 'Other'], dtype=object)

In [ ]:
df['Residence_type'].unique()

array(['Urban', 'Rural'], dtype=object)

In [ ]:
df['smoking_status'].unique()

array(['formerly smoked', 'never smoked', 'smokes', 'Unknown'],
      dtype=object)

In [ ]:
df['bmi'] = df['bmi'].fillna(round (df['bmi'].mean(), 1))
df.isnull().sum()

id                   0
gender               0
age                  0
hypertension         0
heart_disease        0
ever_married         0
work_type            0
Residence_type       0
avg_glucose_level    0
bmi                  0
smoking_status       0
stroke               0
dtype: int64

In [ ]:
df['age_cat'] = pd.cut(df['age'], bins = [0,13,18, 40,60,200],
labels = ['Anak-anak', 'Remaja', 'Dewasa Muda', 'Dewasa Tua', 'Lanjut Usia'])

df['avg_glucose_level_cat'] = pd.cut(df['avg_glucose_level'], bins = [0,70,140,200,1000],
labels = ['Rendah', 'Normal', 'Tinggi', 'Sangat Tinggi'])

df['bmi_cat'] = pd.cut(df['bmi'], bins = [0, 19, 25, 30 ,10000],
labels = ['Kekurangan', 'Ideal', 'Kelebihan', 'Obesitas'])
df

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke,age_cat,avg_glucose_level_cat,bmi_cat
0,9046,Male,67,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1,Lanjut Usia,Sangat Tinggi,Obesitas
1,51676,Female,61,0,0,Yes,Self-employed,Rural,202.21,28.9,never smoked,1,Lanjut Usia,Sangat Tinggi,Kelebihan
2,31112,Male,80,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1,Lanjut Usia,Normal,Obesitas
3,60182,Female,49,0,0,Yes,Private,Urban,171.23,34.4,smokes,1,Dewasa Tua,Tinggi,Obesitas
4,1665,Female,79,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1,Lanjut Usia,Tinggi,Ideal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5105,18234,Female,80,1,0,Yes,Private,Urban,83.75,28.9,never smoked,0,Lanjut Usia,Normal,Kelebihan
5106,44873,Female,81,0,0,Yes,Self-employed,Urban,125.20,40.0,never smoked,0,Lanjut Usia,Normal,Obesitas
5107,19723,Female,35,0,0,Yes,Self-employed,Rural,82.99,30.6,never smoked,0,Dewasa Muda,Normal,Obesitas
5108,37544,Male,51,0,0,Yes,Private,Rural,166.29,25.6,formerly smoked,0,Dewasa Tua,Tinggi,Kelebihan
5109,44679,Female,44,0,0,Yes,Govt_job,Urban,85.28,26.2,Unknown,0,Dewasa Tua,Normal,Kelebihan

In [ ]:
df['stroke'].replace({0:'Tidak Stroke',1:'Stroke'}).value_counts()

stroke
Tidak Stroke    4861
Stroke           249
Name: count, dtype: int64

In [ ]:
labels = df['stroke'].replace({0:'Tidak Stroke',1:'Stroke'}).value_counts(sort=True).index
sizes = df['stroke'].value_counts(sort=True)

In [ ]:
labels = df['stroke'].replace({0:'Tidak Stroke',1:'Stroke'}).value_counts(sort=True).index
sizes = df['stroke'].value_counts(sort=True)

fig = px.pie(names=labels, values=sizes, hole=0.3, color_discrete_sequence=["lightblue","red"],
             labels={'names':'Status Stroke'},
             title='Perbandingan Status Stroke')
fig.update_traces(textposition='inside', textinfo='percent+label+value')

fig.show()

In [ ]:
stroke = 1
data_stroke = df[df['stroke'] == 1]
data_stroke

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke,age_cat,avg_glucose_level_cat,bmi_cat
0,9046,Male,67,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1,Lanjut Usia,Sangat Tinggi,Obesitas
1,51676,Female,61,0,0,Yes,Self-employed,Rural,202.21,28.9,never smoked,1,Lanjut Usia,Sangat Tinggi,Kelebihan
2,31112,Male,80,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1,Lanjut Usia,Normal,Obesitas
3,60182,Female,49,0,0,Yes,Private,Urban,171.23,34.4,smokes,1,Dewasa Tua,Tinggi,Obesitas
4,1665,Female,79,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1,Lanjut Usia,Tinggi,Ideal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
244,17739,Male,57,0,0,Yes,Private,Rural,84.96,36.7,Unknown,1,Dewasa Tua,Normal,Obesitas
245,49669,Female,14,0,0,No,children,Rural,57.93,30.9,Unknown,1,Remaja,Rendah,Obesitas
246,27153,Female,75,0,0,Yes,Self-employed,Rural,78.80,29.3,formerly smoked,1,Lanjut Usia,Normal,Kelebihan
247,34060,Male,71,1,0,Yes,Self-employed,Rural,87.80,28.9,Unknown,1,Lanjut Usia,Normal,Kelebihan
248,43424,Female,78,0,0,Yes,Private,Rural,78.81,19.6,Unknown,1,Lanjut Usia,Normal,Ideal

In [20]:
fig = px.histogram(data_stroke, x='age', nbins=50)

fig.update_layout(
    title='Persebaran Jumlah Pasien yang Terkena Stroke Berdasarkan Usia',
    xaxis_title = 'kategori usia',
    yaxis_title = 'Stroke',
    showlegend = True
)


fig.show()

In [21]:
data_gender = data_stroke[['gender','stroke']].groupby('gender').sum().reset_index()
data_gender

   gender  stroke
0  Female     141
1    Male     108

In [22]:
fig = px.pie(data_gender, names = 'gender', values= 'stroke',
             labels={'names': 'Gender'},
             title= 'Perbandingan Pasien Stroke Berdasarkan Gender', color= 'gender')
fig.update_traces(textposition='inside', textinfo='percent+label+value')

fig.show()

In [23]:
fig= px.violin(data_frame=data_stroke, x="gender", y="age",color = 'gender',box=True,points="all")

fig.update_layout(title="Persebaran Umur Pasien yang Mengidap Stroke Berdasarkan Gender", xaxis_title="\nGender", yaxis_title="age")

fig.show()

In [24]:
data_ever_married = data_stroke[['ever_married','stroke']].groupby('ever_married').sum().reset_index()
data_ever_married

  ever_married  stroke
0           No      29
1          Yes     220

In [25]:
fig = px.bar(data_ever_married, x= 'ever_married', y = 'stroke',color= 'ever_married',title= 'Pasien Stroke Berdasarkan Status Pernikahan', text_auto = True)
fig.show()

In [26]:
data_residence_type = data_stroke[['Residence_type','stroke']].groupby('Residence_type').sum().reset_index()
data_residence_type

  Residence_type  stroke
0          Rural     114
1          Urban     135

In [27]:
fig = px.bar(data_residence_type, x= 'stroke', y = 'Residence_type',color= 'Residence_type',title= 'Pasien Stroke Berdasarkan Jenis Lingkungan Tempat Tinggal', text_auto = True, orientation='h')
fig.show()

In [28]:
data_work_type = data_stroke[['work_type','gender','stroke']].groupby(['work_type','gender']).sum().reset_index()
data_work_type

       work_type  gender  stroke
0       Govt_job  Female      23
1       Govt_job    Male      10
2        Private  Female      76
3        Private    Male      73
4  Self-employed  Female      40
5  Self-employed    Male      25
6       children  Female       2

In [29]:
fig = px.bar(data_work_type, x = 'work_type', y = 'stroke', color= 'gender', barmode= 'group', title= 'Pasien Stroke Berdasarkan Jenis Pekerjaan dan Gender', text_auto = True)
fig.show()

In [30]:
data_heart_tension = data_stroke[['hypertension','heart_disease','stroke']].groupby(['hypertension','heart_disease']).sum().reset_index()
data_heart_tension[['hypertension','heart_disease']] = data_heart_tension[['hypertension','heart_disease']].replace({0 : 'NO', 1 : 'YES'})
data_heart_tension = data_heart_tension.pivot_table(index='hypertension', columns='heart_disease', values='stroke')
data_heart_tension

heart_disease     NO   YES
hypertension
NO             149.0  34.0
YES             53.0  13.0

In [31]:
fig = px.imshow(data_heart_tension, text_auto = True, color_continuous_scale=['lightgreen','green'],
                title = 'Pasien Stroke Berdasarkan Status Darah Tinggi dan Penyakit Jantung')
fig.show()

In [32]:
data_bmi = data_stroke[['bmi','gender','stroke']].groupby(['bmi','gender']).sum().reset_index()
data_bmi

      bmi  gender  stroke
0    16.9  Female       1
1    19.4  Female       1
2    19.6  Female       1
3    20.1  Female       1
4    20.2    Male       1
..    ...     ...     ...
157  45.9    Male       1
158  46.0  Female       1
159  47.5  Female       1
160  48.9  Female       1
161  56.6  Female       1

[162 rows x 3 columns]

In [33]:
fig = px.histogram(data_bmi, x= 'bmi', y= 'stroke', color = 'gender')

fig.update_layout(barmode='overlay')

fig.update_traces(opacity=0.75)
fig.show()

In [34]:
data_glukosa = data_stroke[['avg_glucose_level','stroke']].groupby(['avg_glucose_level']).sum().reset_index()
data_glukosa

     avg_glucose_level  stroke
0                56.11       1
1                57.92       1
2                57.93       1
3                58.09       1
4                58.57       1
..                 ...     ...
243             250.89       1
244             252.72       1
245             259.63       1
246             263.32       1
247             271.74       1

[248 rows x 2 columns]

In [35]:
fig = px.histogram(data_glukosa, x= 'avg_glucose_level', y= 'stroke', nbins=50)

fig.show()

In [36]:
data_smoking_status = data_stroke[['smoking_status','stroke']].groupby(['smoking_status']).sum().reset_index()
data_smoking_status

    smoking_status  stroke
0          Unknown      47
1  formerly smoked      70
2     never smoked      90
3           smokes      42

In [37]:
fig = px.pie(data_smoking_status, names = 'smoking_status', values= 'stroke',
             labels={'names': 'Status Stroke'},
             title= 'Perbandingan Pasien Stroke Berdasarkan Status Merokok', color_discrete_sequence=px.colors.qualitative.Set3)
fig.update_traces(textposition='inside', textinfo='percent+label+value')

fig.show()

In [38]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [39]:
pred_data = df
label_encoder = LabelEncoder()
categorical_cols = ['gender', 'ever_married', 'work_type', 'Residence_type', 'smoking_status', 'age_cat', 'avg_glucose_level_cat', 'bmi_cat']

for col in categorical_cols:
  pred_data[col]= label_encoder.fit_transform(pred_data[col])
pred_data

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke,age_cat,avg_glucose_level_cat,bmi_cat
0,9046,1,67,0,1,1,2,1,228.69,36.6,1,1,3,2,3
1,51676,0,61,0,0,1,3,0,202.21,28.9,2,1,3,2,2
2,31112,1,80,0,1,1,2,0,105.92,32.5,2,1,3,0,3
3,60182,0,49,0,0,1,2,1,171.23,34.4,3,1,2,3,3
4,1665,0,79,1,0,1,3,0,174.12,24.0,2,1,3,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5105,18234,0,80,1,0,1,2,1,83.75,28.9,2,0,3,0,2
5106,44873,0,81,0,0,1,3,1,125.20,40.0,2,0,3,0,3
5107,19723,0,35,0,0,1,3,0,82.99,30.6,2,0,1,0,3
5108,37544,1,51,0,0,1,2,0,166.29,25.6,1,0,2,3,2
5109,44679,0,44,0,0,1,0,1,85.28,26.2,0,0,2,0,2

In [40]:
x = df.drop(['stroke'],axis =1)
y = df["stroke"]

In [41]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=100)
print(f"Shape of training data : {x_train.shape}, {y_train.shape}")
print(f"shape of testing data : {x_test.shape}, {y_test.shape}")

Shape of training data : (3577, 14), (3577,)
shape of testing data : (1533, 14), (1533,)

In [42]:
neighbors = list(range(1, 21))
cv_scores = []
for k in neighbors:
  knn = KNeighborsClassifier(n_neighbors=k)
  scores = cross_val_score(knn, x_train, y_train, cv=5, scoring='accuracy')
  cv_scores.append(scores.mean())

In [43]:
best_k = neighbors[cv_scores.index(max(cv_scores))]
print("Best n_neighbors:", best_k)

Best n_neighbors: 4

In [44]:
knn = KNeighborsClassifier(n_neighbors=best_k)
knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=4)

In [45]:
knn_pred = knn.predict(x_test)
knn_conf = confusion_matrix(y_test, knn_pred)
knn_report = classification_report(y_test, knn_pred)

In [46]:
knn_acc = round(accuracy_score(y_test, knn_pred)*100, ndigits = 2)
print(f"Confusion Matrix : \n\n{knn_conf}")
print(f"\nClassification Report : \n\n{knn_report}")
print(f"\nThe Accuracy of K-Nearest Neighbors Classifier is {knn_acc} %")

Confusion Matrix :

[[1463    1]
 [  69    0]]

Classification Report :

              precision    recall  f1-score   support

           0       0.95      1.00      0.98      1464
           1       0.00      0.00      0.00        69

    accuracy                           0.95      1533
   macro avg       0.48      0.50      0.49      1533
weighted avg       0.91      0.95      0.93      1533


The Accuracy of K-Nearest Neighbors Classifier is 95.43 %

**EVALUASI**
Hasil evaluasi diatas sebagai mencari solusi dari permasalahan model. salah satu teknik yang dapat digunakan adalah oversampling dan salah satu metodenya adalah menggunakan Synthetic Minority Over-Sampling Technique (SMOTE). Oversampling digunakan untuk menangani ketidakseimbangan kelas dalam dataset. ketidakseimbangan kelas terjadi karena jumlah sampel dalam satu kelas jauh lebih sedikit daripada kelas lainnya. jika diterapkan dalam dataset ini, jumlah pasien yang mengalami stroke (minoritas) jauh lebih sedikit dibandingkan dengan pasien yang mengalami stroke. Oversampling membuat kelas minoritas menjadi lebih seimbang dengan kelas mayoritas sehingga model dapat mempelajari pola dengan lebih baik dan memberikan prediksi yang lebih akurat.

In [47]:
!pip install imblearn

Collecting imblearn
  Downloading imblearn-0.0-py2.py3-none-any.whl.metadata (355 bytes)
Requirement already satisfied: imbalanced-learn in /usr/local/lib/python3.12/dist-packages (from imblearn) (0.14.1)
Requirement already satisfied: numpy<3,>=1.25.2 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn->imblearn) (2.0.2)
Requirement already satisfied: scipy<2,>=1.11.4 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn->imblearn) (1.16.3)
Requirement already satisfied: scikit-learn<2,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn->imblearn) (1.6.1)
Requirement already satisfied: sklearn-compat<0.2,>=0.1.5 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn->imblearn) (0.1.5)
Requirement already satisfied: joblib<2,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn->imblearn) (1.5.3)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn->imblearn) (3.6.0)
Downloading imblearn-0.0-py2.py3-none-any.whl (1.9 kB)
Installing collected packages: imblearn
Successfully installed imblearn-0.0

In [48]:
from imblearn.over_sampling import SMOTE

In [49]:
x = df.drop(['stroke', 'id'], axis=1)
y = df["stroke"]

In [50]:
smote = SMOTE()

x_resampled, y_resampled = smote.fit_resample(x, y)
print('shape of x : ', x_resampled.shape)
print('shape of y : ', y_resampled.shape)

shape of x :  (9722, 13)
shape of y :  (9722,)

In [51]:
x_train, x_test, y_train, y_test = train_test_split(x_resampled, y_resampled, test_size=0.3, random_state=100)
print(f"Shape of training data : {x_train.shape}, {y_train.shape}")
print(f"Shape of testing data : {x_test.shape}, {y_test.shape}")

Shape of training data : (6805, 13), (6805,)
Shape of testing data : (2917, 13), (2917,)

In [52]:
neighbors = list(range(1, 21))
cv_scores = []
for k in neighbors:
  knn = KNeighborsClassifier(n_neighbors=k)
  scores = cross_val_score(knn, x_train, y_train, cv=5, scoring='accuracy')
  cv_scores.append(scores.mean())

In [53]:
knn = KNeighborsClassifier(n_neighbors=best_k)
knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=4)

In [54]:
knn_pred = knn.predict(x_test)
knn_conf = confusion_matrix(y_test, knn_pred)
knn_report = classification_report(y_test, knn_pred)
knn_acc = round(accuracy_score(y_test, knn_pred)*100, ndigits = 2)
print(f"Confusion Matrix : \n\n{knn_conf}")
print(f"\nClassification Report : \n\n{knn_report}")
print(f"\nThe Accuracy of K-Nearest Neighbors Classifier is {knn_acc} %")

Confusion Matrix :

[[1232  211]
 [  37 1437]]

Classification Report :

              precision    recall  f1-score   support

           0       0.97      0.85      0.91      1443
           1       0.87      0.97      0.92      1474

    accuracy                           0.91      2917
   macro avg       0.92      0.91      0.91      2917
weighted avg       0.92      0.91      0.91      2917


The Accuracy of K-Nearest Neighbors Classifier is 91.5 %